config/routes.rb
Rails.application.routes.draw do

# 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

  scope module: :public do

    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    # get 'items' => 'items#index'
    # get 'items/:id' => 'items#show', as: 'item'

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' =>'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    # get 'cart_items' => 'cart_items#index'
    # patch 'cart_items/:id' => 'cart_items#update'
    # delete 'cart_items/:id' => 'cart_items#destroy', as: 'destroy_item'
    # post 'cart_items' => 'cart_items#create', as: 'create_item'

    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#comfirm'
    resources :orders, only: [:new, :create, :index , :show]
    # get 'orders/new' => 'orders#new'
    # post 'orders' => 'orders#create'
    # get 'orders' => 'orders#index'
    # get 'orders/:id' => 'orders#show', as: 'order'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    # get 'addresses' => 'addresses#index'
    # post 'addresses' => 'addresses#create'
    # get 'addresses/:id/edit' => 'addresses#edit', as: 'edit_address'
    # patch 'addresses/:id' => 'addresses#update'
    # delete 'addresses/:id' => 'addresses#destroy', as: 'destroy_address'

    get 'search' => 'searches#search'

  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do

    root to: 'homes#top'

    resources :items, only: [:index, :new,:create, :show, :edit, :update]
    # get 'items' => 'items#index'
    # get 'items/new' => 'items#new'
    # post 'items' => 'items#create', as: 'create_item'
    # get 'items/:id' => 'items#show', as: 'item'
    # get 'items/:id/edit' => 'items#edit', as: 'edit_item'
    # patch 'items/:id' => 'items#update', as: 'update_item'

    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres' => 'genres#index'
    # post 'genres' => 'genres#create'
    # get 'genres/:id/edit' => 'genres#edit', as: 'edit_genre'
    # patch 'genres/:id' => 'genres#update', as: 'update_genre'

    resources :customers, only: [:index, :show, :edit, :update]
    # get 'customers' => 'customers#index'
    # get 'customers/:id' => 'customers#show', as: 'customer'
    # get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
    # patch 'customers/:id' => 'customers#update'

    resources :orders, only: [:show, :update]
    # get 'orders/:id' => 'orders#show', as: 'order'
    # patch 'orders/:id' => 'orders#update'

    resources :order_details, only: [:update]
    # patch 'orders/:order_id/order_details/:id' => 'order_details#update', as: 'order_detail'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  # カート内商品
  has_many :cart_items, dependent: :destroy

  # 注文詳細
  has_many :order_details, dependent: :destroy

  # ジャンル
  belongs_to :genre

  # 画像投稿機能
  has_one_attached :image

  # 画像を表示する関数を定義
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

  # 検索機能用
  def self.search_for(content)
    Item.where('name LIKE ?', '%'+content+'%')
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  # 管理者のみが特定の内容を扱えるように制限
  before_action :admin_scan, only: [:index, :new, :create, :show, :edit, :update]

  def index
    @items = Item.all.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def new
    @item = Item.new
  end

  def create
    # binding.pry
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "You have created item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:notice] = "You have updated item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

# 投稿データのストロングパラメータ
private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end

  def admin_scan
    unless current_admin
      redirect_to new_admin_session_path
    end
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-9 offset-1">
      <span class="h4">商品編集</span>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2">
      <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>商品画像</td>
              <td><%= f.file_field :image, accept: "image/*" %><td>
            </tr>
            <tr>
              <td>商品名</td>
              <td><%= f.text_field :name, autofocus: true, placeholder: "商品名" %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= f.text_area :introduction, placeholder: "商品説明" %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= f.select :genre_id, Genre.all.map { |category| [category.name, category.id] }, {include_blank: '--選択してください--'} %></td>
            </tr>
            <tr>
              <td>税抜価格</td>
              <td><%= f.number_field :price, placeholder: "税抜価格" %>円</td>
            </tr>
            <tr>
              <td>販売ステータス</td>
              <td>
                  <%= f.radio_button :is_active, true, checked: true %>
                  <%= f.label :is_active, "販売中", value: true %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "販売停止中", value: false %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit '変更を保存', class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class='row'>
    <div class='col-7 offset-2 mt-5 mb-3'>
      <span class="h4">商品一覧</span>
    </div>
    <div class='col-3 mt-5 mb-3'>
      <%= link_to '新規登録', new_admin_item_path %>
    </div>
  </div>
  <div class='row'>
    <div class='col-10 offset-1'>
      <table class="table table-borderless">
        <thead>
          <tr class="table-secondary">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <td class= <%= item.is_active ? "text-success" : "text-muted" %>>
                <strong><%= item.is_active ? "販売中" : "販売停止中" %></strong>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="col-4 offset-4 mt-5">
          <%= paginate @items %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class='row'>
    <div class='col-9 offset-2 mt-5 mb-3'>
      <span class="h4">商品新規登録</span>
    </div>
  </div>
  <div class='row'>
    <div class='col-8 offset-2'>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><%= f.label :image, "商品画像" %></td>
              <td><%= f.file_field :image, accept: "image/*" %><td>
            </tr>
            <tr>
              <td><%= f.label :name, "商品名" %></td>
              <td><%= f.text_field :name, autofocus: true, placeholder: "商品名" %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, "商品説明" %></td>
              <td><%= f.text_area :introduction, placeholder: "商品説明" %></td>
            </tr>
            <tr>
              <td><%= f.label :genre_id, "ジャンル" %></td>
              <td><%= f.select :genre_id, Genre.all.map { |category| [category.name, category.id] }, {include_blank: '--選択してください--'} %></td>
            </tr>
            <tr>
              <td><%= f.label :price, "税抜価格" %></td>
              <td><%= f.number_field :price, placeholder: "税抜価格" %>円</td>
            </tr>
            <tr>
              <td><%= f.label :is_active, "販売ステータス" %></td>
              <td>
                  <%= f.radio_button :is_active, true, checked: true %>
                  <%= f.label :is_active, "販売中", value: true %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "販売停止中", value: false %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit '新規登録', class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-9 offset-1">
      <span class="h4">商品詳細</span>
    </div>
  </div>
  <div class="row">
    <div class="col-3 pl-3">
      <%= image_tag @item.get_image, size: "180x150" %>
    </div>
    <div class="col-6">
      <table class="table table-borderless right">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre_id %></td>
          </tr>
          <tr>
            <td>
              税込価格<br>
              (税抜価格)
            </td>
            <td><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td class= <%= @item.is_active ? "text-success" : "text-muted" %>>
              <strong><%= @item.is_active ? "販売中" : "販売停止中" %></strong>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 offset-4">
      <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>