config/routes.rb
Rails.application.routes.draw do

# 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

  scope module: :public do

    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    # get 'items' => 'items#index'
    # get 'items/:id' => 'items#show', as: 'item'

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' =>'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    # get 'cart_items' => 'cart_items#index'
    # patch 'cart_items/:id' => 'cart_items#update'
    # delete 'cart_items/:id' => 'cart_items#destroy', as: 'destroy_item'
    # post 'cart_items' => 'cart_items#create', as: 'create_item'

    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#comfirm'
    resources :orders, only: [:new, :create, :index , :show]
    # get 'orders/new' => 'orders#new'
    # post 'orders' => 'orders#create'
    # get 'orders' => 'orders#index'
    # get 'orders/:id' => 'orders#show', as: 'order'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    # get 'addresses' => 'addresses#index'
    # post 'addresses' => 'addresses#create'
    # get 'addresses/:id/edit' => 'addresses#edit', as: 'edit_address'
    # patch 'addresses/:id' => 'addresses#update'
    # delete 'addresses/:id' => 'addresses#destroy', as: 'destroy_address'

    get 'search' => 'searches#search'

  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do

    root to: 'homes#top'

    resources :items, only: [:index, :new,:create, :show, :edit, :update]
    # get 'items' => 'items#index'
    # get 'items/new' => 'items#new'
    # post 'items' => 'items#create', as: 'create_item'
    # get 'items/:id' => 'items#show', as: 'item'
    # get 'items/:id/edit' => 'items#edit', as: 'edit_item'
    # patch 'items/:id' => 'items#update', as: 'update_item'

    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres' => 'genres#index'
    # post 'genres' => 'genres#create'
    # get 'genres/:id/edit' => 'genres#edit', as: 'edit_genre'
    # patch 'genres/:id' => 'genres#update', as: 'update_genre'

    resources :customers, only: [:index, :show, :edit, :update]
    # get 'customers' => 'customers#index'
    # get 'customers/:id' => 'customers#show', as: 'customer'
    # get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
    # patch 'customers/:id' => 'customers#update'

    resources :orders, only: [:show, :update]
    # get 'orders/:id' => 'orders#show', as: 'order'
    # patch 'orders/:id' => 'orders#update'

    resources :order_details, only: [:update]
    # patch 'orders/:order_id/order_details/:id' => 'order_details#update', as: 'order_detail'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # ログイン機能
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # カート内商品
  has_many :cart_items, dependent: :destroy

  # 注文
  has_many :orders, dependent: :destroy

  # 配送先
  has_many :addresses, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :admin_scan, only: [:index, :show, :edit, :update]

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    customer.save
    flash[:notice] = "顧客情報を編集しました。"
    redirect_to admin_customer_path
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
    end

    def admin_scan
      unless current_admin
        redirect_to new_admin_session_path
      end
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-5 mb-3">
    <div class="col-9 offset-1">
      <span class="h4"><strong><%= @customer.last_name %><%= @customer.first_name %></strong></span>
      <span class="h4">さんの</span>
      <span class="h4"><strong>会員情報</strong></span>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch, local: true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td><%= f.label "氏名" %></td>
              <td><%= f.text_field :last_name, placeholder: "令和", autofocus: true %>　<%= f.text_field :first_name, placeholder: "道子" %></td>
            </tr>
            <tr>
              <td><%= f.label "フリガナ" %></td>
              <td><%= f.text_field :last_name_kana, placeholder: "レイワ" %>　<%= f.text_field :first_name_kana, placeholder: "ミチコ" %></td>
            </tr>
            <tr>
              <td><%= f.label "郵便番号" %></td>
              <td><%= f.text_field :postal_code, placeholder: "0000000" %></td>
            </tr>
            <tr>
              <td><%= f.label "住所" %></td>
              <td><%= f.text_field :address, placeholder: "東京都渋谷区代々木神園町0-0", class: "w-100" %></td>
            </tr>
            <tr>
              <td><%= f.label "電話番号" %></td>
              <td><%= f.text_field :telephone_number, placeholder: "00000000000" %></td>
            </tr>
            <tr>
              <td><%= f.label "メールアドレス" %></td>
              <td><%= f.text_field :email, placeholder: "sample@example.com" %></td>
            </tr>
            <tr>
              <td><%= f.label "会員ステータス" %></td>
              <td>
                <%= f.radio_button :is_deleted, false, checked: false %>
                <%= f.label:is_deleted, "有効", value: false %>
                <%= f.radio_button :is_deleted, true, checked: true %>
                <%= f.label:is_deleted, "退会", value: true %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存",class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mt-5 mb-3">
    <div class="col-9 offset-1">
      <span class="h4">会員一覧</span>
    </div>
  </div>
  <div class="row">
    <div class="col-9 offset-2">
      <table class="table">
        <thead class="table-secondary">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer.id) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td class= <%= customer.is_deleted ? "text-muted" : "text-success" %>>
                <strong><%= customer.is_deleted ? "退会" : "有効" %></strong>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 offset-4 mt-5">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-5 mb-3">
    <div class="col-9 offset-1">
      <span class="h4"><strong><%= @customer.last_name %><%= @customer.first_name %></strong></span>
      <span class="h4">さんの</span>
      <span class="h4"><strong>会員情報</strong></span>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td class= <%= @customer.is_deleted ? "text-muted" : "text-success" %>>
              <strong><%= @customer.is_deleted ? "退会" : "有効" %></strong>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-4">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_root_path(customer_id: @customer.id), class: "btn btn-primary" %>
    </div>
  </div>
</div>