config/routes.rb
Rails.application.routes.draw do

# 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

  scope module: :public do

    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    # get 'items' => 'items#index'
    # get 'items/:id' => 'items#show', as: 'item'

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' =>'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    # get 'cart_items' => 'cart_items#index'
    # patch 'cart_items/:id' => 'cart_items#update'
    # delete 'cart_items/:id' => 'cart_items#destroy', as: 'destroy_item'
    # post 'cart_items' => 'cart_items#create', as: 'create_item'

    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#comfirm'
    resources :orders, only: [:new, :create, :index , :show]
    # get 'orders/new' => 'orders#new'
    # post 'orders' => 'orders#create'
    # get 'orders' => 'orders#index'
    # get 'orders/:id' => 'orders#show', as: 'order'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    # get 'addresses' => 'addresses#index'
    # post 'addresses' => 'addresses#create'
    # get 'addresses/:id/edit' => 'addresses#edit', as: 'edit_address'
    # patch 'addresses/:id' => 'addresses#update'
    # delete 'addresses/:id' => 'addresses#destroy', as: 'destroy_address'

    get 'search' => 'searches#search'

  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do

    root to: 'homes#top'

    resources :items, only: [:index, :new,:create, :show, :edit, :update]
    # get 'items' => 'items#index'
    # get 'items/new' => 'items#new'
    # post 'items' => 'items#create', as: 'create_item'
    # get 'items/:id' => 'items#show', as: 'item'
    # get 'items/:id/edit' => 'items#edit', as: 'edit_item'
    # patch 'items/:id' => 'items#update', as: 'update_item'

    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres' => 'genres#index'
    # post 'genres' => 'genres#create'
    # get 'genres/:id/edit' => 'genres#edit', as: 'edit_genre'
    # patch 'genres/:id' => 'genres#update', as: 'update_genre'

    resources :customers, only: [:index, :show, :edit, :update]
    # get 'customers' => 'customers#index'
    # get 'customers/:id' => 'customers#show', as: 'customer'
    # get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
    # patch 'customers/:id' => 'customers#update'

    resources :orders, only: [:show, :update]
    # get 'orders/:id' => 'orders#show', as: 'order'
    # patch 'orders/:id' => 'orders#update'

    resources :order_details, only: [:update]
    # patch 'orders/:order_id/order_details/:id' => 'order_details#update', as: 'order_detail'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  # 会員
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # ログイン機能
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 画像投稿機能
  has_one_attached :image

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  # 会員
  belongs_to :customer

  # 商品
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # ログイン機能
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # カート内商品
  has_many :cart_items, dependent: :destroy

  # 注文
  has_many :orders, dependent: :destroy

  # 配送先
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord

  # 商品
  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  # カート内商品
  has_many :cart_items, dependent: :destroy

  # 注文詳細
  has_many :order_details, dependent: :destroy

  # ジャンル
  belongs_to :genre

  # 画像投稿機能
  has_one_attached :image

  # 画像を表示する関数を定義
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

  # 検索機能用
  def self.search_for(content)
    Item.where('name LIKE ?', '%'+content+'%')
  end

end

app/models/order.rb
class Order < ApplicationRecord

  # 会員
  belongs_to :customer

  # カート内商品
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0,transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

  def subtotal
    sum = 0
    order_details.each do |order_detail|
      sum += order_detail.price * order_detail.amount
    end
    sum
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  # 注文
  belongs_to :order

  # 商品
  belongs_to :item

  enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, in_production: 2, completion_of_production: 3 }

  def subtotal
    price * amount
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :admin_scan, only: [:top]

  def top
    if params[:customer_id].present?
      @customer = Customer.find(params[:customer_id])
      @orders = Order.where(customer_id: params[:customer_id]).order(created_at: :DESC).page(params[:page]).per(10)
    else
      @orders = Order.all.order(created_at: :DESC).page(params[:page]).per(10)
    end
  end

  private

  def admin_scan
    unless current_admin
      redirect_to new_admin_session_path
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  # 管理者のみが特定の内容を扱えるように制限
  before_action :admin_scan, only: [:index, :new, :create, :show, :edit, :update]

  def index
    @items = Item.all.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def new
    @item = Item.new
  end

  def create
    # binding.pry
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "You have created item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:notice] = "You have updated item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

# 投稿データのストロングパラメータ
private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end

  def admin_scan
    unless current_admin
      redirect_to new_admin_session_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if customer_signed_in? %>
              <ul class="navbar-nav mr-auto">
                <%= link_to root_path, class: "header-logo-letter" do %>
                  <%= image_tag 'no_image.jpg', class: 'admin_shop_logo' %>
                <% end %>
              </ul>
              <nav class="nav navbar-nav">
                <span class="client-name  login-client-name">
                  ようこそ、<%= current_customer.last_name %><%= current_customer.first_name %>さん！
                </span>
              </nav>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <%= link_to 'マイページ', customers_my_page_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              </ul>
            <% elsif admin_signed_in? %>
              <ul class="navbar-nav mr-auto">
                <%= link_to admin_root_path, class: "header-logo-letter" do %>
                  <%= image_tag 'no_image.jpg', class: 'admin_shop_logo' %>
                <% end %>
              </ul>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav mr-auto">
                <%= link_to root_path, class: "header-logo-letter" do %>
                  <%= image_tag 'no_image.jpg', class: 'admin_shop_logo' %>
                <% end %>
              </ul>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <%= link_to "About", about_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= render 'public/searches/search' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>